### ISSUE TITLE
How do I disable players teleporting to spawn every time they login.

### ISSUE THREAD

**Issue by SidebottomsCOCclan** [DavideBlade/Clash-of-Minecrafters#11]
### Tasks

- [X] I have read the [wiki](https://github.com/DavideBlade/Clash-of-Minecrafters/wiki).
- [ ] I tried to ask the [community](https://www.spigotmc.org/threads/190277) for help.

### Description

Hi how do I disable the players teleporting to spawn.

### Plugin version

3.0

**Comment by DavideBlade** [comment]
Hi, thanks for the request and for using the appropriate template. Currently it is not possible to do this, but actually it does not make much sense.
From the next version I will include the possibility to disable it. It will probably be possible to do this by simply deleting the "Default spawn" line from the config.yml. What do you think?

**Comment by DavideBlade** [comment]
Feature added in version 3.0.1 ([#ce007e5](https://github.com/DavideBlade/Clash-of-Minecrafters/commit/ce007e5cd09d400181a2e175f0ad788640caf46f)). Thanks again for the suggestion!

**Comment by SidebottomsCOCclan** [comment]
Thank you very much. Very cool and epic. I hope the great Floopa blesses your day
