### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mmuziek** [DavideBlade/Clash-of-Minecrafters#3]
`Could not load 'plugins\CoM.jar' in folder 'plugins' 25.05 14:41:14 [Server] INFO org.bukkit.plugin.InvalidPluginException: main class`a.a.a.a.a' does not extend JavaPlugin 25.05 14:41:14 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:73) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16] 25.05 14:41:14 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16] 25.05 14:41:14 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16] 25.05 14:41:14 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16] 25.05 14:41:14 [Server] INFO at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugins(CraftServer.java:296) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16] 25.05 14:41:14 [Server] INFO at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:200) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16] 25.05 14:41:14 [Server] INFO at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:532) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16] 25.05 14:41:14 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_77] 25.05 14:41:14 [Server] INFO Caused by: java.lang.ClassCastException: interface a.a.a.a.a 25.05 14:41:14 [Server] INFO at java.lang.Class.asSubclass(Unknown Source) ~[?:1.8.0_77] 25.05 14:41:14 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:71) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16] 25.05 14:41:14 [Server] INFO ... 7 more`
i get this error on the last build please fix this as soon as possible

**Comment by DavideBlade** [comment]
What .jar you use? What java version have you installed?

**Comment by mmuziek** [comment]
Java 8 and the last update

**Comment by DavideBlade** [comment]
You use spigot.jar or other .jar for start your server?

**Comment by mmuziek** [comment]
Spigot of course 1.9.4 to be exact

**Comment by DavideBlade** [comment]
Fixed.

Thanks for report.
