### ISSUE TITLE
clan leave error

### ISSUE THREAD

**Issue by mmuziek** [DavideBlade/Clash-of-Minecrafters#4]
here is the error i encounter when using /clan leave

`25.05 16:58:43 [Server] ERROR null 25.05 16:58:43 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'clan' in plugin CoM v1.1 25.05 16:58:43 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16] 25.05 16:58:43 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16] 25.05 16:58:43 [Server] INFO at org.bukkit.craftbukkit.v1_9_R2.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16] 25.05 16:58:43 [Server] INFO at net.minecraft.server.v1_9_R2.PlayerConnection.handleCommand(PlayerConnection.java:1349) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16] 25.05 16:58:43 [Server] INFO at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1184) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16] 25.05 16:58:43 [Server] INFO at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16] 25.05 16:58:43 [Server] INFO at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16] 25.05 16:58:43 [Server] INFO at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16] 25.05 16:58:43 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_77] 25.05 16:58:43 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_77] 25.05 16:58:43 [Server] INFO at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16] 25.05 16:58:43 [Server] INFO at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16] 25.05 16:58:43 [Server] INFO at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16] 25.05 16:58:43 [Server] INFO at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16] 25.05 16:58:43 [Server] INFO at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16] 25.05 16:58:43 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_77] 25.05 16:58:43 [Server] INFO Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1 25.05 16:58:43 [Server] INFO at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_77] 25.05 16:58:43 [Server] INFO at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_77] 25.05 16:58:43 [Server] INFO at com.gmail.davideblade99.clashofminecrafters.e.d.e(ClanUtilities.java:59) ~[?:?] 25.05 16:58:43 [Server] INFO at com.gmail.davideblade99.clashofminecrafters.a.c.onCommand(ClanCommand.java:78) ~[?:?] 25.05 16:58:43 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16] 25.05 16:58:43 [Server] INFO ... 15 more`

**Comment by DavideBlade** [comment]
Fixed.

Thanks for report.
