### ISSUE TITLE
the shop?

### ISSUE THREAD

**Issue by skull4024** [DavideBlade/Clash-of-Minecrafters#5]
well when I do /shop the gui come's up but when I try to use it doesn't work and idk why can u tell me why?

**Comment by DavideBlade** [comment]
Sorry for the late reply but I've been busy. When you click on the item, do you get any errors in the console? Does the item return to its place in the GUI or does it remain in your hand? Do you receive any message in chat?

**Comment by DavideBlade** [comment]
Since version 3.0, the problem is solved. Thanks for the report.
